### ISSUE TITLE
No flights found in file from FR24

### ISSUE THREAD

**Issue by mrman486** [johanohly/AirTrail#65] opened 2024-10-11 08:33 UTC
### The bug

I am testing the import function.

FR24 I get a message saying no flights found from the csv file. I have checked the file and it has many lines in there.

I have tested similar data from an export of app in the air and it works ok

### Operating System that is running AirTrail

Docker

### AirTrail Version

0.31

### Reproduction steps

1. Click upload file
2.Click import
3. Message comes up bottom right there are no flights in the file
...

So far I am really enjoying what you have done with this. Keep up the good work

**Comment by johanohly** [comment] 2024-10-12 14:24
Thank you for reporting this issue.
I am currently on vacation for another week, but when I am back I would need to see the file you are trying to import. 
If you are not comfortable with sharing your flight data with me, that is totally fine, but I probably won't be able to find the root cause of your issue.

**Comment by mrman486** [comment] 2024-10-15 02:18
Happy to directly send you my import file to find out whats wrong with it.

Thank you

**Comment by johanohly** [comment] 2024-10-24 19:55
Thank you again for reporting this issue and providing me with your erroneous import file. 

This is fixed in the next release, I will close this issue to keep track of which issues still need my attention.

**Closed by johanohly** 2024-10-24 19:55 UTC
