### ISSUE TITLE
[Bug] Re-edit flight information automatically added extra date

### ISSUE THREAD

**Issue by Tech-dea** [johanohly/AirTrail#45] opened 2024-09-23 15:39 UTC
### The bug

When you attempted to edit the flight information, each time clicking edit, departure or arrival will automatically added one date (say originally is Sep 8, 2024, when I click edit, it will change to Sep 9, 2024), if I save it and click edit again, it will jump to Sep 10, 2024

### Operating System that is running AirTrail

Debian

### AirTrail Version

latest

### Reproduction steps

1. Go to edit a flight after creation
2. Immediately can see either departure date / arrival date added one extra date

**Comment by johanohly** [comment] 2024-09-23 19:29
I actually remember this happening in development once. I am fairly certain it is an edge-case happening due to times being close to midnight and time zone conversions.

I would appreciate it very much if you could provide your origin, destination, date and time for the flight you're experiencing.
My theory is the date doesn't really play a role here, so you may also modify the date if you are not comfortable sharing your exact flight.

Thank you for reporting this!

**Comment by johanohly** [comment] 2024-10-24 19:54
I am very confident this will be fixed in the next release. 
I sadly can't be sure as you haven't provided a reproducible example, so I am gonna close this issue for now.

**Closed by johanohly** 2024-10-24 19:54 UTC
