### ISSUE TITLE
After saving a flight, searching a callsign for a second flight freezes the page

### ISSUE THREAD

**Issue by efhakim** [johanohly/AirTrail#67] opened 2024-10-12 09:16 UTC
### The bug

Whenever you add a flight with the search flight function, after wanting to add another flight, the search flight function freezes the whole web app.

Happens everytime, maybe it is having issues overwriting a variable app. I don't see anything flagrant in the code but I don't really know much about svelte.

### Operating System that is running AirTrail

Ubuntu

### AirTrail Version

v0.3.1

### Reproduction steps

- New flight, search by callsign number, fill date and time and seat.
- Save
- Add new flight, search by callsign number: freeze happens

**Comment by johanohly** [comment] 2024-10-12 14:07
Thank you for reporting this issue. 
Unfortunately, I am currently on holiday and do not have access to my laptop, so I won’t be able to debug or address the issue for about a week. 
I’ll prioritize investigating and resolving this as soon as I’m back, as adding flights is one of the most used and important features.

**Comment by shomilsaini** [comment] 2024-10-14 22:45
The issue is not related to a specific callsign, I believe there is some issue. Here is the profile from Firefox when seraching. You can see the CPU pegged at 100% and page crashes.
![image](https://github.com/user-attachments/assets/7ef571bc-5dd1-4757-878f-826985ff1bea)

Thanks!

**Comment by Arcturuss** [comment] 2024-10-17 17:05
Searching for an airport freezes the page too.

**Comment by johanohly** [comment] 2024-10-19 19:34
I experienced the same problem, but couldn't pinpoint it. Not sure how to go about finding the root cause of this one.

**Comment by mrkrnz** [comment] 2024-10-25 09:55
subsequent try to search a new airport also freezes at my end.

**Comment by johanohly** [comment] 2024-10-25 11:33
> subsequent try to search a new airport also freezes at my end.

Yep, I also encountered both of these issues while developing a different feature.
I have tried debugging it a bit but there's not even an error, it's super weird.

**Comment by efhakim** [comment] 2024-10-28 08:24
FlightNumber.svelte function lookUpFlight does not return anything, may this be?

**Closed** 2024-10-29 16:56 UTC

**Comment by johanohly** [comment] 2024-11-02 21:14
This has been fixed in v1.0.0!
